name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: PHPUnit Tests
        uses: php-actions/phpunit@v2
        with:
          php_extensions: FFI
          bootstrap: vendor/autoload.php
          args: --coverage-text